#!/usr/bin/env python3
import argparse
import importlib.util
import io
import json
import os
import shutil
import struct
import subprocess
import sys
import time
from pathlib import Path

import torch


ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.config_loader import add_config_arg, apply_config_defaults, load_config
from src.models.int16_reference import DMCIInt16Reference, DMCInt16Reference


def ensure_required_extensions():
    if importlib.util.find_spec("MLCodec_extensions_cpp") is None:
        raise SystemExit(
            "Required extension MLCodec_extensions_cpp is not installed.\n"
            "Install it with:\n"
            "  python -m pip install --no-build-isolation ./src/cpp\n"
            "Or run:\n"
            "  python bootstrap_runtime.py"
        )


ensure_required_extensions()

from src.utils.stream_helper import (
    NalType,
    SPSHelper,
    read_header,
    read_ip_remaining,
    read_sps_remaining,
)
from src.utils.transforms import yuv_444_to_420
from src.utils.video_writer import YUV420Writer


def parse_args():
    parser = argparse.ArgumentParser(
        description="Standalone DCVC-RT INT16 decoder: .bin -> .mp4"
    )
    add_config_arg(parser)
    parser.add_argument(
        "--input_bin",
        type=str,
        required=True,
        help="Input .bin path generated by encode_mp4_to_bin.py",
    )
    parser.add_argument(
        "--bundle_path",
        type=str,
        default="models/int16_bundle_v1.0.0.pt",
        help="Path to the local int16 reference bundle.",
    )
    parser.add_argument(
        "--output_mp4",
        type=str,
        default=None,
        help="Output MP4 path. Defaults to <input_bin>_decoded.mp4.",
    )
    parser.add_argument(
        "--fps",
        type=float,
        default=None,
        help="Override output MP4 fps. If omitted, decoder uses the encoder sidecar JSON when present.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda:0" if torch.cuda.is_available() else "cpu",
        help="Torch device, e.g. cuda:0 or cpu.",
    )
    parser.add_argument(
        "--warmup_skip",
        type=int,
        default=10,
        help="Frames skipped when reporting average steady-state decode time.",
    )
    parser.add_argument(
        "--keep_yuv",
        action="store_true",
        help="Keep the temporary raw YUV file written before MP4 muxing.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show full Python tracebacks for setup/debug failures.",
    )

    known, _ = parser.parse_known_args()
    cfg = load_config(known.config)
    apply_config_defaults(parser, cfg, "decode")

    return parser.parse_args()


def resolve_path(path_str):
    path = Path(path_str)
    if not path.is_absolute():
        path = (ROOT / path).resolve()
    return path


def run_command(command):
    executable = command[0]
    if shutil.which(executable) is None:
        raise RuntimeError(
            f"Required command not found: {executable}. "
            "Install FFmpeg and make sure ffmpeg/ffprobe are on PATH."
        )
    completed = subprocess.run(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        raise RuntimeError(
            f"Command failed ({completed.returncode}): {' '.join(command)}\n"
            f"stdout:\n{completed.stdout}\n"
            f"stderr:\n{completed.stderr}"
        )
    return completed


def synchronize(device):
    if torch.device(device).type == "cuda":
        torch.cuda.synchronize(device=device)


def get_padding_size(height, width, p=16):
    new_h = (height + p - 1) // p * p
    new_w = (width + p - 1) // p * p
    return new_w - width, new_h - height


def load_models(bundle_path, device):
    bundle_blob = torch.load(bundle_path, map_location="cpu", weights_only=False)
    bundle_models = bundle_blob["models"] if "models" in bundle_blob else bundle_blob
    i_frame_net = DMCIInt16Reference(bundle_models["i_frame_net"]).to(device).eval()
    p_frame_net = DMCInt16Reference(bundle_models["p_frame_net"]).to(device).eval()
    return i_frame_net, p_frame_net


def load_sidecar_metadata(input_bin):
    metadata_path = input_bin.with_suffix(".json")
    if not metadata_path.exists():
        return None, None
    with open(metadata_path, "r", encoding="utf-8") as fp:
        return json.load(fp), metadata_path


def default_output_mp4(input_bin):
    return input_bin.with_name(f"{input_bin.stem}_decoded.mp4")


def decode_bin_to_mp4(args):
    input_bin = resolve_path(args.input_bin)
    if not input_bin.exists():
        raise FileNotFoundError(f"Input bitstream not found: {input_bin}")

    bundle_path = resolve_path(args.bundle_path)
    if not bundle_path.exists():
        raise FileNotFoundError(f"Int16 bundle not found: {bundle_path}")

    output_mp4 = resolve_path(args.output_mp4) if args.output_mp4 else default_output_mp4(input_bin)
    output_mp4.parent.mkdir(parents=True, exist_ok=True)
    yuv_path = output_mp4.with_name(f"{output_mp4.stem}_temp.yuv")
    metrics_path = output_mp4.with_name(f"{output_mp4.stem}_decode.json")

    sidecar, sidecar_path = load_sidecar_metadata(input_bin)
    fps = float(args.fps if args.fps is not None else (sidecar.get("fps") if sidecar else 30.0))
    fps_source = "argument" if args.fps is not None else ("sidecar_json" if sidecar else "default_30fps")

    device = torch.device(args.device)
    if device.type == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA device requested but torch.cuda.is_available() is False.")
        torch.cuda.set_device(device)

    i_frame_net, p_frame_net = load_models(bundle_path, device)

    sps_helper = SPSHelper()
    with open(input_bin, "rb") as f:
        input_buff = io.BytesIO(f.read())

    recon_writer = None
    width = None
    height = None
    decode_times = []
    decoded_count = 0
    metadata_initialized = False
    p_frame_net.set_curr_poc(0)

    decode_t0 = time.perf_counter()
    with torch.no_grad():
        while True:
            try:
                header = read_header(input_buff)
            except (EOFError, struct.error):
                break

            while header["nal_type"] == NalType.NAL_SPS:
                sps = read_sps_remaining(input_buff, header["sps_id"])
                sps_helper.add_sps_by_id(sps)
                try:
                    header = read_header(input_buff)
                except (EOFError, struct.error):
                    header = None
                    break
            if header is None:
                break

            sps_id = header["sps_id"]
            sps = sps_helper.get_sps_by_id(sps_id)
            if sps is None:
                raise RuntimeError(f"Missing SPS {sps_id} before frame payload.")

            if recon_writer is None:
                width = int(sps["width"])
                height = int(sps["height"])
                recon_writer = YUV420Writer(str(yuv_path), width, height)

            if not metadata_initialized:
                padding_r, padding_b = get_padding_size(height, width, 16)
                padded_height = height + padding_b
                padded_width = width + padding_r
                if hasattr(i_frame_net, "init_cuda_graph"):
                    i_frame_net.init_cuda_graph(padded_height, padded_width)
                metadata_initialized = True

            qp, bit_stream = read_ip_remaining(input_buff)

            synchronize(device)
            frame_t0 = time.perf_counter()

            if header["nal_type"] == NalType.NAL_I:
                decoded = i_frame_net.decompress(bit_stream, sps, qp)
                p_frame_net.clear_dpb()
                p_frame_net.add_ref_frame(None, decoded["x_hat"])
            elif header["nal_type"] == NalType.NAL_P:
                if sps["use_ada_i"]:
                    p_frame_net.reset_ref_feature()
                decoded = p_frame_net.decompress(bit_stream, sps, qp)
            else:
                raise RuntimeError(f"Unsupported NAL type: {header['nal_type']}")

            synchronize(device)
            decode_times.append(time.perf_counter() - frame_t0)

            x_hat = decoded["x_hat"][:, :, :height, :width]
            y_rec, uv_rec = yuv_444_to_420(x_hat)
            y_rec = (
                torch.clamp(y_rec * 255.0, 0, 255)
                .round()
                .to(dtype=torch.uint8)
                .squeeze(0)
                .cpu()
                .numpy()
            )
            uv_rec = (
                torch.clamp(uv_rec * 255.0, 0, 255)
                .round()
                .to(dtype=torch.uint8)
                .squeeze(0)
                .cpu()
                .numpy()
            )
            recon_writer.write_one_frame(y_rec, uv_rec)
            decoded_count += 1

    total_decode_time = time.perf_counter() - decode_t0

    if recon_writer is None or width is None or height is None:
        raise RuntimeError("Decoder could not recover stream metadata from the bitstream.")

    recon_writer.close()

    mux_t0 = time.perf_counter()
    run_command(
        [
            "ffmpeg",
            "-y",
            "-v",
            "error",
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p",
            "-s",
            f"{width}x{height}",
            "-r",
            str(fps),
            "-i",
            str(yuv_path),
            "-c:v",
            "libx264",
            "-crf",
            "18",
            "-preset",
            "fast",
            str(output_mp4),
        ]
    )
    mux_time = time.perf_counter() - mux_t0

    if not args.keep_yuv and yuv_path.exists():
        os.remove(yuv_path)
        temp_yuv_deleted = True
    else:
        temp_yuv_deleted = False

    effective_skip = min(max(args.warmup_skip, 0), max(len(decode_times) - 1, 0))
    steady_times = decode_times[effective_skip:] if decode_times else []
    avg_decode_time = sum(steady_times) / len(steady_times) if steady_times else 0.0

    metrics = {
        "codec": "dcvc_rt_int16",
        "mode": "decode",
        "input_bin": str(input_bin),
        "bundle_path": str(bundle_path),
        "sidecar_json": str(sidecar_path) if sidecar_path else None,
        "output_mp4": str(output_mp4),
        "temp_yuv": str(yuv_path),
        "temp_yuv_deleted": bool(temp_yuv_deleted),
        "frames_decoded": int(decoded_count),
        "width": int(width),
        "height": int(height),
        "fps": float(fps),
        "fps_source": fps_source,
        "device": str(device),
        "total_decode_time_sec": float(total_decode_time),
        "total_decode_time_min": float(total_decode_time / 60.0),
        "avg_frame_decode_time_sec": float(avg_decode_time),
        "avg_frame_decode_time_ms": float(avg_decode_time * 1000.0),
        "warmup_skip_frames": int(effective_skip),
        "total_mux_time_sec": float(mux_time),
    }

    with open(metrics_path, "w", encoding="utf-8") as fp:
        json.dump(metrics, fp, indent=2)

    print(json.dumps(metrics, indent=2))


def main():
    args = parse_args()
    try:
        decode_bin_to_mp4(args)
    except (FileNotFoundError, RuntimeError, ValueError) as exc:
        if args.verbose:
            raise
        raise SystemExit(f"ERROR: {exc}") from None


if __name__ == "__main__":
    main()
